#
# Blog Settings
#
author: Eefje Hendriks
year: 2014


# Github repositories
github_repo_url: https://github.com/Haacked/haacked.com/

# Disqus Comments
disqus_short_name: EefjeHendriks
disqus_show_comment_count: true

# Google Analytics
# google_analytics_tracking_id: UA-XXXXXXXX


# SASS Configuration
sass:
  sass_dir: _sass

# Jekyll Configuration
markdown: redcarpet
redcarpet:
  extensions: ["tables"]
permalink: /archive/:year/:month/:day/:title/
paginate: 5
paginate_path: "/blog/page/:num"
category_dir: categories
