#
# Blog Settings
#
author: Eefje Hendriks
year: 2014

# Google Analytics
# google_analytics_tracking_id: UA-XXXXXXXX


# SASS Configuration
sass:
  sass_dir: _sass

# Jekyll Configuration
markdown: redcarpet
redcarpet:
  extensions: ["tables"]
permalink: /archive/:year/:month/:day/:title/
paginate: 2
paginate_path: "/blog/page/:num"
category_dir: categories
